### ISSUE TITLE
Packing values

### ISSUE THREAD

**Issue by z3t0** [CarletonURocketry/CU-in-Space-2018-Avionics-Software#1]
https://github.com/CarletonURocketry/CU-in-Space-2018-Avionics-Software/blob/ffa95b5cd857202cf310c447d6b197623c222c94/CU-in-Space-2018-Avionics-Software/telemetry_format.h#L17

The values do not seem to be packed when I was compiling locally using gcc.

Using #pragma pack(1) enabled packing the structs.

**Comment by samueldewan** [comment]
We are compiling with -fpack-struct since the AVRs memory is byte addressable, so alignment is not a concern (we also use -funsigned-bitfields, which may also be relevant).

When using this file on other architectures you may need to be aware of alignment. It should work fine on X86 and ARM, although there may be some small performance penalty.
